version: '2'
services:
  #data container
  data:
    image: debian:jessie
    volumes:
      - ../backend:/var/www/leagueplay

  #mongodb container
  mongodb:
    build: mongodb

  #webserver container
  node:
    build: node
    volumes_from:
      - data:rw
    ports:
      - "3000"

  # Nginx Web Proxy.
  nginx:
    build: nginx
    depends_on:
      - node
    volumes_from:
      - data:ro
    ports:
      - "3000:80"